#!/usr/bin/env bash

cwd="$(cd "$(dirname "$0")" && pwd)"
dir=$(mktemp -d -t fly-build-kaltura-client.XXXXX)

tidy () {
    rm -rf "$dir"
}

trap tidy EXIT

mkdir "$dir/version"
echo TEST_VERSION > "$dir/version/version"

fly --target ci execute \
    --input source="$cwd" \
    --input version="$dir/version" \
    --config "$cwd/pipeline/build.yml"
