---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: source
- name: version

caches:
- path: source/.gradle
- path: source/dependency-check-cache

run:
  path: source/pipeline/build.sh
