---
jobs:
- name: external-tests
  public: true
  plan:
  - get: once-per-weekday
    trigger: true
  - get: source
    trigger: true
    params:
      depth: 1
  - put: version
    params:
      pre: rc
  - task: contract-test
    file: source/pipeline/contract-test.yml
    params:
      PARTNER_ID: ((kaltura-client.partner-id))
      USER_ID: ((kaltura-client.user-id))
      SECRET: ((kaltura-client.secret))
      CAPTION_PROVIDER_API_KEY: ((3play.api-key))
      CAPTION_PROVIDER_HOSTNAME: "api.3playmedia.com"

- name: cut-release
  public: false
  plan:
  - get: source
    params:
      depth: 1
    passed: [external-tests]
  - get: version
    passed: [external-tests]
    params:
      bump: final
  - put: source
    params:
      repository: source
      tag: version/version
  - put: version
    params:
      bump: patch

- name: major
  plan:
    - put: version
      params:
        bump: major

- name: minor
  plan:
    - put: version
      params:
        bump: minor

resources:
- name: source
  type: git
  source:
    branch: main
    private_key: ((kaltura-client.repo-key))
    uri: git@github.com:knowledgemotion/kaltura-client.git

- name: version
  type: semver
  source:
    initial_version: "0.0.0"
    driver: git
    uri: git@github.com:knowledgemotion/versions.git
    branch: main
    file: kaltura-client
    private_key: ((versions.repo-key))

- name: once-per-weekday
  type: time
  source:
    start: "08:30"
    stop: "20:00"
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]
    location: Europe/London
