package com.boclips.kalturaclient.captionasset;

import java.util.Arrays;

public enum KalturaLanguage {
    ABAZA("Abaza"),
    ABKHAZIAN("Abkhazian"),
    ABNAKI_WESTERN("Abnaki Western"),
    ABURE("Abure"),
    ACHANG("Achang"),
    ACHINESE("Achinese"),
    ACHTERHOOKS("Achterhooks"),
    ACHUMAWI("Achumawi"),
    ADIOUKROU("Adioukrou"),
    ADYGHE_ADYGEI("Adyghe; Adygei"),
    ADYNYAMATHANHA("Adynyamathanha"),
    AFADE("Afade"),
    AFAR("Afar"),
    AFRIKAANS("Afrikaans"),
    AGHEM("Aghem"),
    AGHUL("Aghul"),
    AGUACATECO("Aguacateco"),
    AGUARUNA("Aguaruna"),
    AINU_JAPAN("Ainu (Japan)"),
    AKKADIAN("Akkadian"),
    AKLANON("Aklanon"),
    AKUM("Akum"),
    ALABAMA("Alabama"),
    ALBANIAN("Albanian"),
    ALBANIAN_GHEG("Albanian (Gheg)"),
    ALBANIAN_TOSK("Albanian (Tosk)"),
    ALEUT("Aleut"),
    ALGONQUIN("Algonquin"),
    ALTAI_SOUTHERN("Altai (Southern)"),
    AMHARIC("Amharic"),
    ANGLOROMANI("Angloromani"),
    APACHE_JICARILLA("Apache (Jicarilla)"),
    APACHE_WESTERN("Apache (Western)"),
    ARABIC("Arabic"),
    ARABIC_STANDARD("Arabic (standard)"),
    ARABIC_TUNISIAN_SPOKEN("Arabic Tunisian Spoken"),
    ARAMAIC("Aramaic"),
    ARAMAIC_SAMARITAN("Aramaic Samaritan"),
    ARAPAHO("Arapaho"),
    ARAUCANIAN("Araucanian"),
    ARIKARA("Arikara"),
    ARMENIAN("Armenian"),
    AROMANIAN("Aromanian"),
    ASSAMESE("Assamese"),
    ASSINIBOINE("Assiniboine"),
    ASSYRIAN_NEO__ARAMAIC("Assyrian Neo-Aramaic"),
    ASTURIAN("Asturian"),
    ATIKAMEKW("Atikamekw"),
    AWADHI("Awadhi"),
    AYMARA("Aymara"),
    AZERBAIJANI("Azerbaijani"),
    BABINE("Babine"),
    BADAGA("Badaga"),
    BAI("Bai"),
    BALINESE("Balinese"),
    BALOCHI_SOUTHERN("Balochi Southern"),
    BALTI("Balti"),
    BALUCHI("Baluchi"),
    BASA_CAMEROON("Basa (Cameroon)"),
    BASHKIR("Bashkir"),
    BASQUE("Basque"),
    BAVARIAN("Bavarian"),
    BEAVER("Beaver"),
    BEJA("Beja"),
    BEMBA_ZAMBIA("Bemba (Zambia)"),
    BENGALI_BANGLA("Bengali (Bangla)"),
    BETAWI("Betawi"),
    BEZHTA("Bezhta"),
    BHILI("Bhili"),
    BHOJPURI("Bhojpuri"),
    BHUTANI("Bhutani"),
    BIHARI("Bihari"),
    BIKOL("Bikol"),
    BINI("Bini"),
    BISHNUPRIYA_MANIPURI("Bishnupriya Manipuri"),
    BISLAMA("Bislama"),
    BRETON("Breton"),
    BUGINESE("Buginese"),
    BULGARIAN("Bulgarian"),
    BURIAT("Buriat"),
    BURMESE("Burmese"),
    BYELORUSSIAN_BELARUSIAN("Byelorussian (Belarusian)"),
    CADDO("Caddo"),
    CAMBODIAN("Cambodian"),
    CANTONESE("Cantonese"),
    CARRIER("Carrier"),
    CARRIER_SOUTHERN("Carrier Southern"),
    CATALAN("Catalan"),
    CATAWBA("Catawba"),
    CAYUGA("Cayuga"),
    CEBUANO("Cebuano"),
    CHAGATAI("Chagatai"),
    CHALDEAN_NEO__ARAMAIC("Chaldean Neo-Aramaic"),
    CHEROKEE("Cherokee"),
    CHEYENNE("Cheyenne"),
    CHICKASAW("Chickasaw"),
    CHILCOTIN("Chilcotin"),
    CHINESE("Chinese"),
    CHINOOKJARGON("Chinook jargon"),
    CHIPEWYAN("Chipewyan"),
    CHIPPEWA("Chippewa"),
    CHOCTAW("Choctaw"),
    CHOR("Chor"),
    CHUKOT("Chukot"),
    CIMBRIAN("Cimbrian"),
    CLALLAM_KLALLAM("Clallam Klallam"),
    COCHIMI("Cochimi"),
    COCOPA("Cocopa"),
    COLOGNIAN("Colognian"),
    COMANCHE("Comanche"),
    COMORIAN("Comorian"),
    COMOX("Comox"),
    COPTIC("Coptic"),
    CORSICAN("Corsican"),
    CREEK("Creek"),
    CRIMEAN_TATAR("Crimean Tatar"),
    CROATIAN("Croatian"),
    CUPEO("Cupeo"),
    CZECH("Czech"),
    DAKOTA("Dakota"),
    DANISH("Danish"),
    DARGWA("Dargwa"),
    DARI_PERSIAN("Dari (Persian)"),
    DARI_ZOROASTRIAN("Dari Zoroastrian"),
    DEHU("Dehu"),
    DELAWARE("Delaware"),
    DINKA("Dinka"),
    DOGRI_GENERIC("Dogri (generic)"),
    DOGRIB("Dogrib"),
    DOLGAN("Dolgan"),
    DONG("Dong"),
    DUALA("Duala"),
    DUNGAN("Dungan"),
    DUTCH("Dutch"),
    DYULA("Dyula"),
    E("E"),
    EMILIAN("Emilian"),
    ENGLISH("English"),
    ENGLISH_AMERICAN("English (American)"),
    ENGLISH_BRITISH("English (British)"),
    ENGLISH_MIDDLE11001500("English Middle (1100-1500)"),
    ERZYA("Erzya"),
    ESPERANTO("Esperanto"),
    ESTONIAN("Estonian"),
    EVEN("Even"),
    EVENKI("Evenki"),
    FAEROESE("Faeroese"),
    FALA("Fala"),
    FANG_EQUATORIAL_GUINEA("Fang (Equatorial Guinea)"),
    FARSI("Farsi"),
    FIJI("Fiji"),
    FILIPINO("Filipino"),
    FINNISH("Finnish"),
    FINNISH_TORNEDALEN("Finnish (Tornedalen)"),
    FON("Fon"),
    FRANCO_PROVE("Franco-Prove"),
    FRANKISH("Frankish"),
    FRENCH("French"),
    FRISIAN("Frisian"),
    FRISIAN_NORTHERN("Frisian Northern"),
    FRIULIAN("Friulian"),
    FUR("Fur"),
    GA("Ga"),
    GAELIC_MANX("Gaelic (Manx)"),
    GAELIC_SCOTTISH("Gaelic (Scottish)"),
    GAGAUZ("Gagauz"),
    GALICIAN("Galician"),
    GAN("Gan"),
    GEEZ("Geez"),
    GEORGIAN("Georgian"),
    GERMAN("German"),
    GERMAN_HUTTERITE("German Hutterite"),
    GERMAN_PENNSYLVANIA("German Pennsylvania"),
    GILBERTESE("Gilbertese"),
    GILYAK_NIVKH("Gilyak Nivkh"),
    GITXSAN("Gitxsan"),
    GREEK("Greek"),
    GREEK_ANCIENT_TO1453("Greek Ancient (to 1453)"),
    GREENLANDIC("Greenlandic"),
    GUARANI("Guarani"),
    GUJARATI("Gujarati"),
    GWICHIN("Gwichin"),
    HAIDA("Haida"),
    HAINANESE("Hainanese"),
    HAISLA("Haisla"),
    HAKKA("Hakka"),
    HALKOMELEM("Halkomelem"),
    HAN("Han"),
    HANI("Hani"),
    HAUSA("Hausa"),
    HAWAIIAN("Hawaiian"),
    HEBREW("Hebrew"),
    HEILTSUK("Heiltsuk"),
    HIDATSA("Hidatsa"),
    HILIGAYNON("Hiligaynon"),
    HINDI("Hindi"),
    HMONG("Hmong"),
    HOKKIEN("Hokkien"),
    HOPI("Hopi"),
    HUIZHOU_CHINESE("Huizhou Chinese"),
    HUNGARIAN("Hungarian"),
    ICELANDIC("Icelandic"),
    IKPOSO("Ikposo"),
    ILOKO("Iloko"),
    INARI_SAMI("Inari Sami"),
    INDONESIAN("Indonesian"),
    INGRIAN("Ingrian"),
    INGUSH("Ingush"),
    INTERLINGUA("Interlingua"),
    INTERLINGUE("Interlingue"),
    INUKTITUT("Inuktitut"),
    INUPIAK("Inupiak"),
    IRISH("Irish"),
    ITALIAN("Italian"),
    ITELMEN("Itelmen"),
    JAPANESE("Japanese"),
    JAVANESE("Javanese"),
    JINYU_CHINESE("Jinyu Chinese"),
    JJU("Jju"),
    JUDEO_CRIMEAN_TATAR("Judeo-Crimean Tatar"),
    JUDEO_GEORGIAN("Judeo-Georgian"),
    JUTISH("Jutish"),
    KABARDIAN("Kabardian"),
    KABUVERDIANU("Kabuverdianu"),
    KABYLE("Kabyle"),
    KACHCHI("Kachchi"),
    KAIKAVIANLITERARYLANGUAGE_KAJKAVIAN("Kaikavian literary language (Kajkavian)"),
    KALMYK_OIRAT("Kalmyk Oirat"),
    KANNADA("Kannada"),
    KANSA("Kansa"),
    KARACHAY_BALKAR("Karachay-Balkar"),
    KARAGAS("Karagas"),
    KARAIM("Karaim"),
    KARAKALPAK("Karakalpak"),
    KARELIAN("Karelian"),
    KASHMIRI("Kashmiri"),
    KASHUBIAN("Kashubian"),
    KASKA("Kaska"),
    KAWI("Kawi"),
    KAZAKH("Kazakh"),
    KHAKAS("Khakas"),
    KHALAJ_TURKIC("Khalaj Turkic"),
    KHANTY("Khanty"),
    KHASI("Khasi"),
    KHMER_NORTHERN("Khmer Northern"),
    KICKAPOO("Kickapoo"),
    KINYARWANDA_RUANDA("Kinyarwanda (Ruanda)"),
    KIOWA("Kiowa"),
    KIRGHIZ("Kirghiz"),
    KIRUNDI_RUNDI("Kirundi (Rundi)"),
    KLINGONTLH_INGAN_HOL("Klingon tlhIngan-Hol"),
    KODAVA("Kodava"),
    KOMI_PERMYAK("Komi-Permyak"),
    KONKANIGENERIC("Konkani (generic)"),
    KONKANISPECIFIC("Konkani (specific)"),
    KONKANI_GOAN("Konkani Goan"),
    KOREAN("Korean"),
    KORYAK("Koryak"),
    KOSRAEAN("Kosraean"),
    KOTAVA("Kotava"),
    KPELLE("Kpelle"),
    KUMIAI("Kumiai"),
    KUMYK("Kumyk"),
    KURDISH("Kurdish"),
    KUTENAI("Kutenai"),
    KWAKIUTL("Kwakiutl"),
    LAAL("Laal"),
    LADIN("Ladin"),
    LADINO("Ladino"),
    LAHNDA("Lahnda"),
    LAHU("Lahu"),
    LAK("Lak"),
    LAKI("Laki"),
    LAKOTA("Lakota"),
    LAOTHIAN("Laothian"),
    LATIN("Latin"),
    LATVIAN_LETTISH("Latvian (Lettish)"),
    LAZ("Laz"),
    LEZGHIAN("Lezghian"),
    LIGURIAN("Ligurian"),
    LILLOOET("Lillooet"),
    LIMBU("Limbu"),
    LIMBURGISH_LIMBURGER("Limburgish ( Limburger)"),
    LINGALA("Lingala"),
    LITHUANIAN("Lithuanian"),
    LOJBAN("Lojban"),
    LOMA_LIBERIA("Loma (Liberia)"),
    LOMBARD("Lombard"),
    LOW_GERMAN_LOW_SAXON("Low German Low Saxon"),
    LOZI("Lozi"),
    LUBA_LULUA("Luba-Lulua"),
    LUCUMI("Lucumi"),
    LUDIAN("Ludian"),
    LULE_SAMI("Lule Sami"),
    LUNDA("Lunda"),
    LUO_KENYA_AND_TANZANIA("Luo (Kenya and Tanzania)"),
    LUSHOOTSEED("Lushootseed"),
    MACEDONIAN("Macedonian"),
    MADURESE("Madurese"),
    MAGAHI("Magahi"),
    MAITHILI("Maithili"),
    MALAGASY("Malagasy"),
    MALAY("Malay"),
    MALAYALAM("Malayalam"),
    MALECITE_PASSAMAQUODDY("Malecite-Passamaquoddy"),
    MALTESE("Maltese"),
    MANCHU("Manchu"),
    MANDAIC("Mandaic"),
    MANDAN("Mandan"),
    MANDARIN_CHINESE("Mandarin Chinese"),
    MANSI("Mansi"),
    MAORI("Maori"),
    MARANAO("Maranao"),
    MARATHI("Marathi"),
    MARI_RUSSIA("Mari (Russia)"),
    MARWARI("Marwari"),
    MASAI("Masai"),
    MAYO("Mayo"),
    MEITEI("Meitei"),
    MENDE_SIERRA_LEONE("Mende (Sierra Leone)"),
    MENOMINEE("Menominee"),
    MICMAC("Micmac"),
    MIN_BEI_CHINESE("Min Bei Chinese"),
    MIN_DONG_CHINESE("Min Dong Chinese"),
    MINANGKABAU("Minangkabau"),
    MINGRELIAN("Mingrelian"),
    MIRANDESE("Mirandese"),
    MOHAWK("Mohawk"),
    MOKSHA("Moksha"),
    MOLDAVIAN("Moldavian"),
    MON("Mon"),
    MONGOLIAN("Mongolian"),
    MORISYEN("Morisyen"),
    MOSSI("Mossi"),
    MOZARABIC("Mozarabic"),
    MULTILINGUAL("Multilingual"),
    MUONG("Muong"),
    NAMA_NAMIBIA("Nama (Namibia)"),
    NANAI("Nanai"),
    NASKAPI("Naskapi"),
    NAURU("Nauru"),
    NEAPOLITAN("Neapolitan"),
    NEPALI("Nepali"),
    NEWARI_NEPAL_BHASA("Newari Nepal Bhasa"),
    NGANASAN("Nganasan"),
    NISGAA("Nisgaa"),
    NIUEAN("Niuean"),
    NOGAI("Nogai"),
    NORSE_OLD("Norse Old"),
    NORTHERN_SOTHO_PEDI_SEPEDI("Northern Sotho Pedi Sepedi"),
    NORWEGIAN("Norwegian"),
    NOVIAL("Novial"),
    NYAMWEZI("Nyamwezi"),
    NYORO("Nyoro"),
    NYUNGAH("Nyungah"),
    OCCITAN("Occitan"),
    OJIBWA_CENTRAL("Ojibwa Central"),
    OJIBWA_EASTERN("Ojibwa Eastern"),
    OJIBWA_NORTHWESTERN("Ojibwa Northwestern"),
    OJIBWA_SEVERN("Ojibwa Severn"),
    OJIBWA_WESTERN("Ojibwa Western"),
    OKINAWAN_CENTRAL("Okinawan Central"),
    OLD_ENGLISH("Old English"),
    ONEIDA("Oneida"),
    ONONDAGA("Onondaga"),
    ORIYA("Oriya"),
    OROMO_AFAN("Oromo (Afan"),
    GALLA("Galla)"),
    OTTAWA("Ottawa"),
    PAIPAI("Paipai"),
    PALAUAN("Palauan"),
    PAMPANGA("Pampanga"),
    PANGASINAN("Pangasinan"),
    PAPIAMENTO("Papiamento"),
    PASHTO_PUSHTO("Pashto (Pushto)"),
    PERSIAN("Persian"),
    PERSIAN_DARI("Persian (Dari)"),
    PFAELZISCH("Pfaelzisch"),
    PICARD("Picard"),
    PIEDMONTESE("Piedmontese"),
    PIRAH("Pirah"),
    PITCAIRN_NORFOLK("Pitcairn-Norfolk"),
    PLAUTDIETSCH("Plautdietsch"),
    POLISH("Polish"),
    PONTIC("Pontic"),
    PORTUGUESE("Portuguese"),
    POTAWATOMI("Potawatomi"),
    PRUSSIAN("Prussian"),
    PULAAR("Pulaar"),
    PUNJABI("Punjabi"),
    QASHQAI("Qashqai"),
    QAWASQAR("Qawasqar"),
    QUECHUA("Quechua"),
    QUICH_CENTRAL("Quich Central"),
    RAPANUI("Rapanui"),
    RAROTONGAN("Rarotongan"),
    RHAETO_ROMANCE("Rhaeto-Romance"),
    ROMAGNOL("Romagnol"),
    ROMANI_KALO_FINNISH("Romani Kalo Finnish"),
    ROMANI_SINTE("Romani Sinte"),
    ROMANIAN("Romanian"),
    ROMANIAN_ISTRO("Romanian Istro"),
    ROMANIAN_MEGLENO("Romanian Megleno"),
    ROMANY("Romany"),
    RUNION_CREOLE_FRENCH("Runion Creole French"),
    RUSSIAN("Russian"),
    RUSYN("Rusyn"),
    SAINT_LUCIAN_CREOLE_FRENCH("Saint Lucian Creole French"),
    SAKHA("Sakha"),
    SALAR("Salar"),
    SALISH_STRAITS("Salish Straits"),
    SAMI_KILDIN("Sami Kildin"),
    SAMOAN("Samoan"),
    SANGRO("Sangro"),
    SANSKRIT("Sanskrit"),
    SANTALI("Santali"),
    SARAMACCAN("Saramaccan"),
    SARDINIAN_SASSARESE("Sardinian Sassarese"),
    SATERLAND_FRISIAN("Saterland Frisian"),
    SAXON_UPPER("Saxon Upper"),
    SCOTS("Scots"),
    SECHELT("Sechelt"),
    SEEDIQ("Seediq"),
    SEKANI("Sekani"),
    SELKUP("Selkup"),
    SENECA("Seneca"),
    SERBIAN("Serbian"),
    SERBO_CROATIAN("Serbo-Croatian"),
    SERI("Seri"),
    SESOTHO("Sesotho"),
    SETSWANA("Setswana"),
    SHAWNEE("Shawnee"),
    SHONA("Shona"),
    SHOR("Shor"),
    SHOSHONI("Shoshoni"),
    SHUSWAP("Shuswap"),
    SICILIAN("Sicilian"),
    SIDAMO("Sidamo"),
    SILESIAN("Silesian"),
    SINDHI("Sindhi"),
    SINHALESE("Sinhalese"),
    SISWATI("Siswati"),
    SKOLT_SAMI("Skolt Sami"),
    SLAVEY_NORTH("Slavey North"),
    SLAVEY_SOUTH("Slavey South"),
    SLOVAK("Slovak"),
    SLOVENIAN("Slovenian"),
    SOMALI("Somali"),
    SONINKE("Soninke"),
    SORBIAN_LOWER("Sorbian Lower"),
    SORBIAN_UPPER("Sorbian Upper"),
    SOUTHERN_SAMI("Southern Sami"),
    SPANISH("Spanish"),
    SRANAN("Sranan"),
    STONEY("Stoney"),
    SUDOVIAN("Sudovian"),
    SUMERIAN("Sumerian"),
    SUNDANESE("Sundanese"),
    SVAN("Svan"),
    SWABIAN("Swabian"),
    SWAHILI_KISWAHILI("Swahili (Kiswahili)"),
    SWEDISH("Swedish"),
    SWEDISH_SIGN_LANGUAGE("Swedish Sign Language"),
    SWISS_GERMAN_ALEMANNIC_ALSATIAN("Swiss German Alemannic Alsatian"),
    SYRIAC("Syriac"),
    TABASSARAN("Tabassaran"),
    TACHAWIT("Tachawit"),
    TACHELHIT("Tachelhit"),
    TAGALOG("Tagalog"),
    TAGBANWA("Tagbanwa"),
    TAGISH("Tagish"),
    TAHLTAN("Tahltan"),
    TAI_NA("Tai Na"),
    TAJIK("Tajik"),
    TALYSH("Talysh"),
    TAMAJAQ_TAWALLAMMAT("Tamajaq Tawallammat"),
    TAMASHEQ("Tamasheq"),
    TAMAZIGHT_CENTRAL_ATLAS("Tamazight Central Atlas"),
    TAMIL("Tamil"),
    TARAHUMARA_CENTRAL("Tarahumara Central"),
    TAT_MUSLIM("Tat Muslim"),
    TATAR("Tatar"),
    TELUGU("Telugu"),
    TEO_CHEW("Teo Chew"),
    TETUM("Tetum"),
    THAI("Thai"),
    THAI_NORTHERN("Thai (Northern)"),
    THAI_NORTHEASTERN("Thai Northeastern"),
    THOMPSON("Thompson"),
    TIBETAN("Tibetan"),
    TIGRE("Tigre"),
    TIGRINYA("Tigrinya"),
    TLINGIT("Tlingit"),
    TODA("Toda"),
    TOHONO_OODHAM("Tohono Oodham"),
    TOK_PISIN("Tok Pisin"),
    TONGA("Tonga"),
    TONGA_NYASA("Tonga (Nyasa)"),
    TSEZ("Tsez"),
    TSIMSHIAN("Tsimshian"),
    TSONGA("Tsonga"),
    TULU("Tulu"),
    TUMBUKA("Tumbuka"),
    TUMZABT("Tumzabt"),
    TUPINAMB("Tupinamb"),
    TURKANA("Turkana"),
    TURKISH("Turkish"),
    TURKISH_OTTOMAN("Turkish Ottoman"),
    TURKMEN("Turkmen"),
    TUSCARORA("Tuscarora"),
    TUVALU("Tuvalu"),
    TUVINIAN("Tuvinian"),
    TWI("Twi"),
    UBYKH("Ubykh"),
    UDI("Udi"),
    UDMURT("Udmurt"),
    UIGHUR("Uighur"),
    UKRAINIAN("Ukrainian"),
    UNDEFINED("Undefined"),
    URDU("Urdu"),
    URUM("Urum"),
    UZBEK("Uzbek"),
    VENETIAN("Venetian"),
    VEPS("Veps"),
    VIETNAMESE("Vietnamese"),
    VOLAPUK("Volapuk"),
    VORO("Voro"),
    VOTIC("Votic"),
    VRO("Vro"),
    WAORANI("Waorani"),
    WARAY_PHILIPPINES("Waray (Philippines)"),
    WELSH("Welsh"),
    WESTERN_FARSI("Western Farsi"),
    WESTERN_NEO_ARAMAIC("Western Neo-Aramaic"),
    WIYOT("Wiyot"),
    WOLOF("Wolof"),
    WU_CHINESE("Wu Chinese"),
    WYMYSORYS("Wymysorys"),
    XHOSA("Xhosa"),
    YANESHA("Yanesha"),
    YIDDISH("Yiddish"),
    YORUBA("Yoruba"),
    ZAPOTEC_ISTHMUS("Zapotec Isthmus"),
    ZARMA("Zarma"),
    ZULU("Zulu");

    private final String name;

    KalturaLanguage(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public static KalturaLanguage fromName(String name) {
        return Arrays.stream(KalturaLanguage.values())
                .filter(lang -> lang.name.equals(name))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("No such language: " + name));
    }
}
