name: Gradle Dependency Graph
on:
  push:
    branches: ['main']
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: Build and generate dependency graph
      uses: gradle/actions/dependency-submission@v3
